import { Language } from './types';

export const TRANSLATIONS = {
  en: {
    appTitle: 'PerfoMate',
    subtitle: 'Image to Perforation Tool',
    uploadTitle: 'Source Image',
    uploadPlaceholder: 'Click to upload or drag image',
    dimensionsTitle: 'Plate Dimensions',
    width: 'Width',
    height: 'Height',
    margin: 'Margin',
    patternTitle: 'Pattern Config',
    spacing: 'Hole Spacing (Pitch)',
    minHole: 'Min Hole Ø',
    maxHole: 'Max Hole Ø',
    invert: 'Invert Colors',
    statsTitle: 'Statistics',
    totalHoles: 'Total Holes',
    openArea: 'Open Area',
    finalSize: 'Final Size',
    export: 'Export SVG',
    generating: 'Generating Pattern...',
    readyTitle: 'Ready to Perforate',
    readyDesc: 'Upload an image in the sidebar to generate a pattern.',
    dragPan: 'Drag to Pan',
    scrollZoom: 'Scroll to Zoom',
    fitScreen: 'Fit to Screen',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out'
  },
  zh: {
    appTitle: 'PerfoMate 穿孔大师',
    subtitle: '图像转穿孔板工具',
    uploadTitle: '源图片',
    uploadPlaceholder: '点击上传或拖拽图片',
    dimensionsTitle: '板材尺寸',
    width: '宽度',
    height: '高度',
    margin: '边距',
    patternTitle: '图案设置',
    spacing: '孔间距 (Pitch)',
    minHole: '最小孔径 Ø',
    maxHole: '最大孔径 Ø',
    invert: '反转颜色',
    statsTitle: '统计信息',
    totalHoles: '总孔数',
    openArea: '穿孔率',
    finalSize: '最终尺寸',
    export: '导出 SVG',
    generating: '正在生成图案...',
    readyTitle: '准备就绪',
    readyDesc: '请在侧边栏上传图片以生成图案',
    dragPan: '拖拽平移',
    scrollZoom: '滚动缩放',
    fitScreen: '适应屏幕',
    zoomIn: '放大',
    zoomOut: '缩小'
  }
};